services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "<get-secured-pw>"
    platform: "linux/amd64"
    ports:
      - "1432:1432"
